---
# This workflow will do renovate bot work

name: RenovateBot

on:
  workflow_dispatch

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "renovate-try/*"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Show Repo
        run: echo "run on ${{ github.repository }}"
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
