---
# This workflow will do renovate bot work

name: RenovateBot

on:
  workflow_dispatch

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Show Repo
        env:
          GH_REPO: ${{ github.repository }}
        run: echo "run on $GH_REPO"
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        env:
          REPO_TOKEN: ${{ secrets.RENOVATE_TOKEN  }}
        uses: renovatebot/github-action@v39.0.1
        with:
          token: "$REPO_TOKEN"
