---
# This workflow will do renovate bot work

name: RenovateBot

on:
  workflow_dispatch

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: echo Token
        run: echo "${{ secrets.RENOVATE_TOKEN }}"
      - name: Checkout
        uses: actions/checkout@v3.5.3
        if: ${{ true }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.1
        if: ${{ true }}
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
